export { default as LoginInput } from "./Logininput";
export { default as MainLoader } from "./MainLoader";
export { default as Alert } from "./Alert";
export { default as Header } from "./Header";
export { default as Home } from "./Home";
export { default as ServicesList } from "./ServicesList";
export { default as MealPlan } from "./MealPlanComponent/MealPlan";
export { default as ExerciseOnly } from "./ExerciseOnlyComponent/ExerciseOnly";
export {default as TheCombined } from "./CombinedComponent/TheCombined";
export {default as AboutUspart } from "./AboutUspart/AboutUspart";
export {default as CoppyRight } from "./CoppyRight";
// export {default as Combined } from "./CombinedComponent/Combined";
